---
zigbee2mqtt_version: "2.8.0"
zigbee2mqtt_image: "docker.io/koenkk/zigbee2mqtt"
zigbee2mqtt_user: "1000"
zigbee2mqtt_data_dir: "/var/home/core/zigbee2mqtt"
zigbee2mqtt_port: "20000"
zigbee2mqtt_timezone: "Europe/Amsterdam"
zigbee2mqtt_device: "/dev/ttyUSB0"
